version: '3.8'

services:

  db:
    image: postgres:12.4
    container_name: yamdb_final_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: sorochinskii/yamdb_final_web:latest
    container_name: yamdb_final_web
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_files:/code/static
      - media_files:/media
    env_file:
      - .env

  nginx: 
    build: nginx/.
    container_name: yamdb_final_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes_from:
      - web
