version: '3.8'

volumes:
  postgres_data:
  static_files:

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api_yamdb/.env

  web:
    build: .
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_files:/code/static
    env_file:
      - ./api_yamdb/.env
    image: yamdb_final

  nginx: 
    build: nginx/.
    ports:
      - 80:80
    depends_on:
      - web
    volumes_from:
      - web
