version: '3.8'

services:

  db:
    image: postgres:12.4
    container_name: yamdb_final_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: sorochinskii/yamdb_final_web:latest
    container_name: yamdb_final_web
    restart: always
    depends_on:
      - db
    volumes:
      - static_files:/yamdb_final_code/static
      - media_files:/media
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: yamdb_final_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_files:/yamdb_final_code/static
      - media_files:/media
      - /yamdb_final_code/nginx/nginx.conf:/etc/nginx/conf.d

volumes:
  postgres_data:
  static_files:
  media_files:
