version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    container_name: postgres
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
    - ./.env

  web:
    image: sorochinskii/yamdb_final_web:latest
    container_name: yamdb_final_web
    restart: always
    depends_on:
      - db
    volumes:
      - static_files:/yamdb_final_code/static
      - media_files:/media
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static_files:/yamdb_final_code/files/static
      - ./media_files:/yamdb_final_code/files/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_files:
  media_files:
  .env:
