version: '3.8'

volumes:
  postgres_data:
  static_files:

services:

  db:
    image: postgres:12.4
    container_name: c_yamdb_final_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    # image: yamdb_final_db

  web:
    build: .
    container_name: c_yamdb_final_web
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_files:/code/static
    env_file:
      - .env
    # image: yamdb_final_web

  nginx: 
    build: nginx/.
    container_name: c_yamdb_final_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes_from:
      - web
    # image: yamdb_final_nginx
